#!/bin/bash

TOOLS_DIR=$(dirname "$(realpath "$0")")

# Source config
. "$TOOLS_DIR/config.sh"

if ! command -v pyside6-uic>/dev/null; then
    echo "Couldn't find \`pyside6-uic\`. Did you forget to activate venv?"
    exit 1
fi

test -d "$PYTHON_UI_DIR" || mkdir -p "$PYTHON_UI_DIR"

for ui_in in "$UI_DIR"/*; do
    ui_out="${PYTHON_UI_DIR}/$(basename "$ui_in" | tr '.' '_').py"
    pyside6-uic "$ui_in" > "$ui_out"
done
